exports.validationRgex = {
    firstName: /^[_ a-zA-Z]{3,36}$/,
    lastName: /^[_ a-zA-Z]{3,36}$/,
    address: /^.{3,300}$/,
    email: /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]*\.([a-zA-Z]{2,4})$/,
    mobileNumber: /^[0-9]{7,15}/,
    gender: /^(male|female)$/,
    country: /^[_ a-zA-Z]{3,300}$/,
    city: /^[_ a-zA-Z]{3,300}$/,
    legalName: /^[_ a-zA-Z]{3,36}$/,
    currency: /^[_a-zA-Z]{3}/,
    commonName: /^[_ a-zA-Z]{3,36}$/,
    mappingId: /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
    userId: "ObjectId",
    merchantId: "ObjectId",
    categories: /^.{3,300}$/,
    contactPerson: /^[_ a-zA-Z]{3,300}$/,
    homapageDesc: /^[_ a-zA-Z]{3,300}$/,
    bio: /^[_ a-zA-Z]{3,300}$/,
}
